version: '3.7'

services:

  mysql:
    container_name: mysql_container
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./dbdata:/var/lib/mysql/
    networks:
      - mysql_net

  adminer:
    container_name: adminer_container
    image: adminer
    depends_on:
      - mysql
    ports:
      - "10100:8080"
    networks:
        - mysql_net

networks:
    mysql_net:
        driver: bridge
